name: CI/CD

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies with Bun
        run: bun install

      - name: Compile project
        run: bun compile

      - name: Lint project
        run: bun lint
