name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

env:
  VITE_BACKEND_URL: ${{ vars.VITE_BACKEND_URL }}
  VITE_BASE_URL: ${{ vars.VITE_BASE_URL }}
permissions:
  contents: read
  pages: write
  packages: write
  id-token: write
concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  front-end:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup project
        run: bun install
      - name: Build
        run: bun fe:build
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'
      - name: Deploy front-end to GitHub pages
        id: deployment
        uses: actions/deploy-pages@v4

  back-end:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/idlerpg:latest
